- name: "breaking-change"
  color: "ee0701"
  description: "A change that changes the API or breaks backward compatibility for users."
- name: "bug"
  color: "ee0701"
  description: "Inconsistencies or issues which will cause a problem for users or implementors."
- name: "documentation"
  color: "0052cc"
  description: "Solely about the documentation of the project."
- name: "enhancement"
  color: "1d76db"
  description: "Enhancement of the code, not introducing new features."
- name: "good first issue"
  color: "0e8a16"
  description: "Good for newcomers."
- name: "help wanted"
  color: "0e8a16"
  description: "We need some extra helping hands or expertise in order to resolve this."
- name: "question"
  color: "cc317c"
  description: "Discussion to determine if an issue is relevant or if more information is needed."
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on."
- name: "dependencies"
  color: "0366d6"
  description: "Updates to dependencies like GoReleaser." 